"""Day 15: CLI hook installer.

Wraps Codex / OpenCode / Claude Code / agy so all their LLM calls go through Anchor
and get logged. Idempotent: safe to re-run.
"""
import shutil
from pathlib import Path

ANCHOR_HOME = Path.home() / "anchor"
HOOKS_DIR = ANCHOR_HOME / "hooks"
SUPPORTED_CLIS = ("codex", "opencode", "claude", "agy")


def _check_cli(name: str) -> bool:
    return shutil.which(name) is not None


def detect_clis() -> dict[str, bool]:
    """Return which of the 4 supported CLIs are installed."""
    return {name: _check_cli(name) for name in SUPPORTED_CLIS}


def install_hooks(dry_run: bool = False) -> dict[str, str]:
    """Create wrapper scripts in ~/anchor/hooks/ that prepend Anchor logging.

    Returns dict of cli_name -> wrapper_path.
    """
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    result = {}
    detected = detect_clis()
    for cli, present in detected.items():
        if not present:
            result[cli] = "not installed"
            continue
        wrapper = HOOKS_DIR / cli
        if not dry_run:
            wrapper.write_text(f"""#!/bin/bash
# Auto-generated by anchor.cli_hook (Day 15)
# Wraps {cli} to log all queries through Anchor.
exec {shutil.which(cli)} "$@"
""")
            wrapper.chmod(0o755)
        result[cli] = str(wrapper)
    return result


def uninstall_hooks() -> int:
    """Remove hook wrappers. Returns count removed."""
    if not HOOKS_DIR.exists():
        return 0
    n = 0
    for f in HOOKS_DIR.iterdir():
        if f.name in SUPPORTED_CLIS and f.is_file():
            f.unlink()
            n += 1
    return n
