"""First-principles quality scoring with async cross-family judge feedback.

Combines local heuristic_quality (cheap, immediate) with sampled panel
judge (expensive, ground truth) to drive quality_feedback overlay.

The judge now compares *worker vs oracle* using a CROSS-FAMILY panel
(v0.9.53, fixes P0-1 oracle self-bias). The oracle reference answer is
generated by `ORACLE_MODEL` (default: minimax-m3, per AGENTS.md spec) and
a runtime-resolved panel of enabled, non-oracle judges votes
on worker-vs-oracle via majority. Cross-family votes cancel judge-worker
overlap biases that a single-Opus judge exhibited (13-17pp, arXiv
2605.07395).

Quality signal in [0, 1]:
  A (worker wins, majority)  -> 1.0
  B (oracle wins, majority)  -> 0.0
  TIE (majority)             -> 0.5

Oracle responses are cached for 1h (in-process LRU) to avoid burning
quota on repeated prompts. Judge API failures are logged as "missing
observation" (NOT TIE) so quality feedback reflects real signal vs.
forced neutral — the previous default-TIE was the bug.

Sampling policy: ANCHOR_JUDGE_SAMPLE_RATE (default 0.1 = 10% of traffic).
"""
from __future__ import annotations

import asyncio
import hashlib
import logging
import os
from typing import Optional

from anchor.judge_cache import get_cached_oracle_response, cache_oracle_response
from anchor.quality_feedback import update_quality_cell

_SAMPLE_RATE: float = float(os.environ.get("ANCHOR_JUDGE_SAMPLE_RATE", "0.1"))


def _should_sample(query: str) -> bool:
    """Deterministic sampling: same query hashes to same decision."""
    h = int(hashlib.sha1(query.encode()).hexdigest()[:8], 16)
    return (h % 1000) < int(_SAMPLE_RATE * 1000)


def local_quality(response: str, latency_ms: int = 0) -> float:
    """Cheap local quality signal in [0, 1]. Always runs synchronously."""
    from anchor.judge_local import heuristic_quality
    return float(heuristic_quality(response, latency_ms=latency_ms))


async def _get_oracle_response(query: str) -> str:
    """Get oracle (ORACLE_MODEL) response for query, using 1h LRU cache.

    Falls back to empty string if cache miss + API call fails. Caller
    treats empty oracle as missing observation (does not record TIE).
    """
    cached = get_cached_oracle_response(query)
    if cached is not None:
        return cached
    from anchor.config import ORACLE_MODEL
    from anchor.judge import _call_opus
    content, _, _, _ = await _call_opus(
        query, max_tokens=4096, judge_model=ORACLE_MODEL,
    )
    if content:
        cache_oracle_response(query, content)
    return content or ""


async def maybe_judge_and_record(
    query: str,
    response: str,
    worker: str,
    category: str,
    difficulty: str,
    *,
    sample_rate: Optional[float] = None,
) -> Optional[float]:
    """Sample-rate gated cross-family panel judge + quality_feedback update.

    response_a = worker response, response_b = oracle (ORACLE_MODEL)
    response. Verdict mapping: A=1.0 (worker better), B=0.0 (oracle
    better), TIE=0.5.

    Returns the observed score if sampled AND panel produced a verdict,
    else None. Returns explicit sentinel `MISSING_OBSERVATION` (a
    module-level string) when judge panel is unavailable or fewer than
    MIN_JUDGE_PANEL_SIZE members responded — caller should record this
    rather than treat as TIE (TIE bias was the P0-1 bug).
    """
    rate = sample_rate if sample_rate is not None else _SAMPLE_RATE
    h = int(hashlib.sha1(query.encode()).hexdigest()[:8], 16)
    if (h % 1000) >= int(rate * 1000):
        return None
    if not response:
        return None
    try:
        oracle_response = await _get_oracle_response(query)
    except Exception as e:
        logging.warning("JUDGE_ORACLE skip %s", e)
        return None
    if not oracle_response:
        return None
    try:
        from anchor.config import MIN_JUDGE_PANEL_SIZE, resolve_judge_panel
        from anchor.judge_calibration import judge_ensemble
        panel = resolve_judge_panel(evaluated_worker=worker)
        if len(panel) < MIN_JUDGE_PANEL_SIZE:
            logging.warning(
                "JUDGE_FEEDBACK missing query=%s worker=%s reason=panel_too_small panel=%s",
                query[:40], worker, panel,
            )
            return MISSING_OBSERVATION
        majority, agreement, per_judge = await judge_ensemble(
            query=query,
            response_a=response,
            response_b=oracle_response,
            panel=panel,
        )
        # Count judges that actually produced A/B/TIE (None = judge failed).
        n_success = sum(1 for v in per_judge.values() if v in ("A", "B", "TIE"))
        if majority is None or n_success < MIN_JUDGE_PANEL_SIZE:
            logging.warning(
                "JUDGE_FEEDBACK missing query=%s worker=%s panel_ok=%d/%d per_judge=%s",
                query[:40], worker, n_success, len(per_judge), per_judge,
            )
            return MISSING_OBSERVATION
        score = {"A": 1.0, "B": 0.0, "TIE": 0.5}.get(majority, 0.5)
        new_score = update_quality_cell(worker, category, difficulty, score)
        logging.info(
            "JUDGE_FEEDBACK sampled query=%s worker=%s majority=%s agreement=%.2f per_judge=%s -> overlay=%.3f",
            query[:40], worker, majority, agreement, per_judge, new_score,
        )
        return new_score
    except Exception as e:
        logging.warning("JUDGE_FEEDBACK skip %s", e)
        return None


# Sentinel returned when judge panel fails — distinct from None (not
# sampled) and from a real numeric score (recorded). Callers should treat
# this as "no observation" and NOT as 0.5 TIE.
MISSING_OBSERVATION: str = "missing"


def record_outcome_with_judge_feedback(
    query: str,
    response: str,
    worker: str,
    category: str,
    difficulty: str,
    latency_ms: int = 0,
) -> float:
    """Synchronous wrapper: returns local_quality; schedules async judge if sampled."""
    local_score = local_quality(response, latency_ms=latency_ms)
    if _should_sample(query):
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                loop.create_task(
                    maybe_judge_and_record(query, response, worker, category, difficulty)
                )
            else:
                loop.run_until_complete(
                    maybe_judge_and_record(query, response, worker, category, difficulty)
                )
        except Exception as e:
            logging.warning("JUDGE_SCHEDULE skip %s", e)
    return local_score


__all__ = [
    "local_quality",
    "maybe_judge_and_record",
    "record_outcome_with_judge_feedback",
    "_SAMPLE_RATE",
    "_get_oracle_response",
]



def quality_tier_proxy(score):
    """Re-export of judge_local.quality_tier for backwards compatibility."""
    from anchor.judge_local import quality_tier
    return quality_tier(score)
